### PR TITLE
Fix swipe animation stuck

### PR DESCRIPTION
**Pull request by axinvd**
The issue with animation getting stuck after a swipe has been fixed

https://github.com/webraptor/react-native-deck-swiper/assets/70860930/10a60c69-a530-4251-af81-96d9e754409e

### CODE REVIEW

**Comment by Sasha95** [comment]
Finally 😁

**Comment by webraptor** [comment]
can you also bump package version, patch value?

**Comment by webraptor** [comment]
merged. will publish to npm within 24h as well.

**Comment by webraptor** [comment]
released on NPM

**Pull request merged**
