### PR TITLE
Fix #13

### LINKED ISSUE #13: Empty cards still tries to render ( From Previous Repo still issue )
Card Index initializes with the maximum Card Index equal to the initial size of the cards Array. And if any element is deleted from cards Array or updated, it iterates over the same range of card indices, hence it will return undefined for items no longer present in Cards Array.

### PR DESCRIPTION
**Pull request by gfpacheco**
I'm new to this package, could you just make sure I didn't break anything else with this change?

I'm re-setting cards indexes and the cards state whenever the cards prop changes.

### CODE REVIEW

**Comment by gfpacheco** [comment]
I could re-set the state only if the length of the cards change if you think that's safer

**Comment by webraptor** [comment]
@gfpacheco using getDerivedStateFromProps isn't really recommended and the swiper actually had it a while back and was removed for multiple reasons, one of which is performance. The current issue mentioned happens likely because there's a mix of state / props in the swiper when there should be only props.

**Comment by gfpacheco** [comment]
I totally agree! I think the cards state is unnecessary, but I wanted to share the code that fixed the issue for me.

At the same time, we need to update the state whenever the cards prop changes (even before the render that changing it would cause), otherwise we might end up trying to read a card from an index that doesn't exist anymore.

**Comment by Rotemy** [comment]
`getDerivedStateFromProps` also fixes an issue for me when the card is null

**Pull request closed without merging**
